# Generated by Django 3.1.2 on 2021-05-20 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20210520_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
