# Generated by Django 3.1.2 on 2021-05-23 23:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210520_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
