# Generated by Django 3.2.3 on 2021-06-08 22:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_departments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='photo_2',
        ),
        migrations.AlterField(
            model_name='professional',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
