# Generated by Django 3.2.3 on 2021-06-08 23:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20210608_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='departments',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='professional',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
