# Generated by Django 3.2.3 on 2021-06-09 00:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20210609_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professional',
            },
        ),
    ]
