# Generated by Django 3.2.3 on 2021-06-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='open',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
