# Generated by Django 3.2.3 on 2021-06-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_4',
        ),
    ]
