# Generated by Django 3.2.3 on 2021-06-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='slug',
        ),
    ]
