# Generated by Django 3.2.3 on 2021-08-28 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_remove_comments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 28, 1, 24, 41, 159453, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
