# Generated by Django 3.2.3 on 2024-04-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_remove_comments_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
