# Generated by Django 3.2.9 on 2022-01-31 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_remove_comments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 31, 15, 16, 4, 461319, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_comment', to='clinic.Comments'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
